--ORACLE
--1.1
SELECT COUNT(1)
  FROM (SELECT A.MSISDN, SUM(A.PV) PV
          FROM CX_JINXJ.PAGEVISIT A, (SELECT * FROM CX_JINXJ.USER_INFO A WHERE A.SEX = 'ÄÐ') B
         WHERE A.MSISDN = B.MSISDN
           AND A.RECORD_DAY BETWEEN '20171001' AND '20171007'
         GROUP BY A.MSISDN
        HAVING SUM(A.PV) > 100) A;

--1.2
SELECT DISTINCT A.MSISDN
  FROM (SELECT A.RECORD_DAY,
               A.MSISDN,
               COUNT(1) OVER(PARTITION BY A.MSISDN, A.DIFF) DAYS
          FROM (SELECT A.MSISDN,
                       A.RECORD_DAY,
                       TO_NUMBER(A.RECORD_DAY) - ROW_NUMBER() OVER(PARTITION BY A.MSISDN ORDER BY A.RECORD_DAY) DIFF
                  FROM (SELECT A.MSISDN, A.RECORD_DAY
                          FROM CX_JINXJ.PAGEVISIT A
                         WHERE A.RECORD_DAY BETWEEN '20171001' AND '20171007'
                         GROUP BY A.MSISDN, A.RECORD_DAY) A) A) A
 WHERE A.DAYS >= 3;

--2.1
SELECT A.DEPT_NAME, A.NAME, A.SALARY
  FROM (SELECT B.DEPT_NAME,
               A.NAME,
               A.SALARY,
               DENSE_RANK() OVER(PARTITION BY B.DEPT_NAME ORDER BY A.SALARY DESC) RAN
          FROM CX_JINXJ.EMPLOYEE A, CX_JINXJ.DEPARTMENT B
         WHERE A.DEPARTMENTID = B.DEPARTMENTID) A
 WHERE A.RAN <= 3;


--3.1
SELECT A.REQUEST_AT,
       ROUND(COUNT(CASE
                     WHEN INSTR(UPPER(A.STATUS), 'CANCELLED') > 0 THEN
                      1
                   END) / COUNT(1),
             2) RATE
  FROM CX_JINXJ.TRIPS A,
       (SELECT * FROM CX_JINXJ.USERS A WHERE UPPER(A.BANNED) = 'YES') B,
       (SELECT * FROM CX_JINXJ.USERS A WHERE UPPER(A.BANNED) = 'YES') C
 WHERE A.CLIEND_ID = B.USER_ID(+)
   AND A.DRIVER_ID = C.USER_ID(+)
   AND B.USER_ID IS NULL
   AND C.USER_ID IS NULL
   AND A.REQUEST_AT BETWEEN '2013-10-01' AND '2013-10-03'
 GROUP BY A.REQUEST_AT;
